name: Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install autossh
        run: sudo apt update && sudo apt install -y autossh openssh-client

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Keep reverse tunnel alive forever
        run: |
          autossh -M 0 \
          -o "ServerAliveInterval 30" \
          -o "ServerAliveCountMax 3" \
          -o StrictHostKeyChecking=no \
          -N -R 0.0.0.0:2222:localhost:22 root@91.107.133.36
